version: "3.8"

services:
  app:
    build:
      context: .
      target: php81
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8007:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "33061:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=tupa
      - MYSQL_PASSWORD=123456789
      - MYSQL_ROOT_PASSWORD=123456789
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data: